/**
 * stateTransition.ts — Frontend Document State Transition Helper
 */

import { STANDARD_STATUS } from './statusModel';

export const VALID_TRANSITIONS: Record<string, string[]> = {
  [STANDARD_STATUS.DRAFT]: [
    STANDARD_STATUS.SUBMITTED,
    STANDARD_STATUS.PENDING_APPROVAL,
    STANDARD_STATUS.APPROVED,
    STANDARD_STATUS.CANCELLED,
  ],
  [STANDARD_STATUS.SUBMITTED]: [
    STANDARD_STATUS.PENDING_APPROVAL,
    STANDARD_STATUS.APPROVED,
    STANDARD_STATUS.RETURNED,
    STANDARD_STATUS.REJECTED,
    STANDARD_STATUS.CANCELLED,
    STANDARD_STATUS.DRAFT,
  ],
  [STANDARD_STATUS.PENDING_APPROVAL]: [
    STANDARD_STATUS.PENDING_APPROVAL,
    STANDARD_STATUS.APPROVED,
    STANDARD_STATUS.REJECTED,
    STANDARD_STATUS.RETURNED,
    STANDARD_STATUS.CANCELLED,
  ],
  [STANDARD_STATUS.APPROVED]: [
    STANDARD_STATUS.COMPLETED,
    STANDARD_STATUS.CANCELLED,
    STANDARD_STATUS.DRAFT,
  ],
  [STANDARD_STATUS.REJECTED]: [
    STANDARD_STATUS.DRAFT,
    STANDARD_STATUS.SUBMITTED,
    STANDARD_STATUS.PENDING_APPROVAL,
    STANDARD_STATUS.CANCELLED,
  ],
  [STANDARD_STATUS.RETURNED]: [
    STANDARD_STATUS.DRAFT,
    STANDARD_STATUS.SUBMITTED,
    STANDARD_STATUS.PENDING_APPROVAL,
    STANDARD_STATUS.CANCELLED,
  ],
  [STANDARD_STATUS.CANCELLED]: [],
  [STANDARD_STATUS.COMPLETED]: [],
};

export function canTransitionTo(currentStatus: string, targetStatus: string): boolean {
  const from = (currentStatus || 'draft').toLowerCase();
  const to = (targetStatus || '').toLowerCase();
  const allowed = VALID_TRANSITIONS[from] || [];
  return allowed.includes(to);
}
